### ISSUE TITLE
showLoader() hideLoader() bug

### ISSUE THREAD

**Issue by AlbertoSamele** [twho/loading-buttons-ios#2]
If you call showLoader() and hideLoader() in quick succession (less than 0.18 seconds apart) the hideLoader() function will not be executed due to the transition animation of 0.2 seconds you've put. This should not happen and a smooth transition should be granted no matter what.
There are workarounds to this using the showLoader closure but I think it should be fixed and taken into account anyways.

Other than this, great work on the repo! Good job!

**Comment by jonchui** [comment]
Good find - i was wracking my brain as to why the spinner was still spinning for us on a local error.

What did you end up doing as a workaround?

**Comment by twho** [comment]
I think a [dispatch barrier](https://developer.apple.com/documentation/dispatch/dispatch_barrier?language=objc) will help. Let me experiment with it and update it to you in a bit.

**Comment by twho** [comment]
I have pushed a new fix to this. Meanwhile, I'll let the issue open until I make another release.

**Comment by twho** [comment]
Please find [new version(0.1.0)](https://github.com/twho/loading-buttons-ios/releases/tag/0.1.0) for the fix.
