### ISSUE TITLE
Looks like with iOS 13, calling hideLoader and showLoader crashes if not called from main thread. 

### ISSUE THREAD

**Issue by jonchui** [twho/loading-buttons-ios#3]
STEPS
1. Call `hideLoader` from background thread. aka when you return from an API async

specifically these 2 lines:
![image](https://user-images.githubusercontent.com/204868/80112563-796eea00-853e-11ea-99cc-6bc9c09f3e3b.png)

EXPECTED:
- `hideLoader`'s UI calls would be wrapped in a `DispatchQueue.main.async { } `, so that the callers don't need to do that?

ACTUAL:
- they're not, so it crashes if not called from the main thread

**Comment by twho** [comment]
Do you want to make a PR for this? Otherwise I can do the fix

**Comment by jonchui** [comment]
Sure if you have time that'd be awesome!

**Comment by dimazen** [comment]
The thing is you don't have to work with UI from the any background thread. That would be unexpected, @jonchui

**Comment by jonchui** [comment]
@dimazen tracking

But often times you use this bc you are doing Asynchronous api calls. 

So in the completion block, rather than always saying explicitly 

`DispatchQueue.main.async { hideLoader }`

If this library wrapped UI calls in that main asynchronous call, you can just call hideLoader from any thread and they would take care of hiding it on the main loop in the next run loop.
