### ISSUE TITLE
button background color change 

### ISSUE THREAD

**Issue by waqarali462** [twho/loading-buttons-ios#6]
Hi,
I am using this pod when i click the button background color is changed but i don't want  change the background
color

**Comment by twho** [comment]
This is our design for the button, if you would like to create your style, you could inherit our `LoadingButton` and **override** the following functions. These are the places I change background colors. 

```swift
open override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesBegan(touches, with: event)
}

open override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
    super.touchesMoved(touches, with: event)
} 
```

**Comment by waqarali462** [comment]
thank you
